[project]
name = "pyconductor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiortc>=1.13.0",
    "flask>=3.1.1",
    "flask-socketio>=5.5.1",
    "mediapipe>=0.10.14",
    "numpy>=2.2.6",
    "opencv-python>=4.11.0.86",
]
