services:
  - type: web
    name: gesture-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python wsgi.py
    envVars:
      - key: PORT
        value: 5000
